version: 1
jobs:
  build:
    docker:
      - image: ubuntu:disco

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get update
            apt-get install -y cmake libboost-dev libboost-test-dev lcov build-essential
      - run:
          name: build
          command: |
            mkdir build
            cd build
            cmake .. $CMAKE_CMD_OPTION
            make -j 2
            make test
      - run:
          name: Print the Current Time
          command: date
