version: 1
jobs:
  build:
    docker:
      - image: ubuntu:disco

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get install cmake libboost-dev libboost-test-dev lcov
      - run:
          name: Greeting
          command: |
            mkdir build
            cd build
            cmake .. $CMAKE_CMD_OPTION
            make -j 2
            make test
      - run:
          name: Print the Current Time
          command: date
