version: 1
jobs:
  build:
    docker:
      - image: ubuntu:xenial

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get update
            apt-get install -y cmake libboost-dev libboost-test-dev lcov build-essential
      - run:
          name: set environment
          command: |
            export CMAKE_CMD_OPTION="-DENABLE_COVERAGE=1"
            export CXX=g++
            export CXX_FOR_BUILD=g++
            export CC_FOR_BUILD=gcc
            gcc --version
      - run:
          name: build
          command: |
            mkdir build
            cd build
            cmake .. $CMAKE_CMD_OPTION
            make -j 2
            pwd
            make test
      - run:
          name: Print the Current Time
          command: date
